/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RouterFactoryInterface extends utils.Interface {
  functions: {
    "createRouter(address,address)": FunctionFragment;
    "createRouterAndAddLiquidity(address,address,address,uint256,bytes)": FunctionFragment;
    "init(address)": FunctionFragment;
    "transactionManager()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "createRouter",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createRouterAndAddLiquidity",
    values: [string, string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "init", values: [string]): string;
  encodeFunctionData(
    functionFragment: "transactionManager",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRouterAndAddLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transactionManager",
    data: BytesLike
  ): Result;

  events: {
    "RouterCreated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RouterCreated"): EventFragment;
}

export type RouterCreatedEvent = TypedEvent<[string], { router: string }>;

export type RouterCreatedEventFilter = TypedEventFilter<RouterCreatedEvent>;

export interface RouterFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RouterFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createRouter(
      signer: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createRouterAndAddLiquidity(
      signer: string,
      recipient: string,
      assetId: string,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    init(
      _transactionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transactionManager(overrides?: CallOverrides): Promise<[string]>;
  };

  createRouter(
    signer: string,
    recipient: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createRouterAndAddLiquidity(
    signer: string,
    recipient: string,
    assetId: string,
    amount: BigNumberish,
    signature: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  init(
    _transactionManager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transactionManager(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    createRouter(
      signer: string,
      recipient: string,
      overrides?: CallOverrides
    ): Promise<string>;

    createRouterAndAddLiquidity(
      signer: string,
      recipient: string,
      assetId: string,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    init(_transactionManager: string, overrides?: CallOverrides): Promise<void>;

    transactionManager(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "RouterCreated(address)"(router?: null): RouterCreatedEventFilter;
    RouterCreated(router?: null): RouterCreatedEventFilter;
  };

  estimateGas: {
    createRouter(
      signer: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createRouterAndAddLiquidity(
      signer: string,
      recipient: string,
      assetId: string,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    init(
      _transactionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transactionManager(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createRouter(
      signer: string,
      recipient: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createRouterAndAddLiquidity(
      signer: string,
      recipient: string,
      assetId: string,
      amount: BigNumberish,
      signature: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    init(
      _transactionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transactionManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
